--- 
pipeline: 
  test_app: 
    image: "node:carbon"
    commands: 
      - "npm i"
      - "npm test"
  publish_to_quay:
    image: plugins/docker
    username: mspencer+drone
    secrets: [ docker_password ]
    repo: quay.squarespace.net/mspencer/shared-dependencies-svc
    registry: quay.squarespace.net
    tags:
      - ${DRONE_COMMIT_BRANCH/\//-}-${DRONE_BUILD_NUMBER}
    when:
      branch: master
